# Generated by Django 3.2.25 on 2025-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='availability',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutors.Subject'),
        ),
    ]
