# Generated by Django 3.2.25 on 2025-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
